# Generated by Django 4.0.6 on 2023-08-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0012_alter_product_archieved_alter_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='product',
            name='archieved',
            field=models.BooleanField(default=False, verbose_name='Product archived?'),
        ),
    ]
